### ISSUE TITLE
Empty ai output.

### ISSUE THREAD

**Issue by Hugoang08** [kimjammer/Neuro#10]
The request proses in the llmWrapper isn't giving any response. any suggestion on how to fix this?

![Screenshot 2024-05-28 074612](https://github.com/kimjammer/Neuro/assets/147172454/48c93770-a1f9-4df2-9b48-82c855dcfa75)
![Screenshot 2024-05-28 074914](https://github.com/kimjammer/Neuro/assets/147172454/c8d6a37f-5c71-4090-acf4-c35efc3562dd)

**Comment by kimjammer** [comment]
Hi there. This is likely not a problem in llmWrapper/Neuro. We can see in your second image that the LLM is only generating one token (the stop token), so it looks like the AI didn't give a response. Please verify that your API (specifically the chat endpoint) is functioning correctly with a tool like Bruno with the system prompt as the prompt. If the API is functioning correctly, you can use neurofrontend's "lobotomy" tab to look at the prompt that is being sent to the LLM. See if there is anything weird there.

**Comment by kimjammer** [comment]
Closing for staleness. Please feel free to reopen if you have further comments.
