### ISSUE TITLE
stream error -9998

### ISSUE THREAD

**Issue by tigers2020** [kimjammer/Neuro#7]
what this mean? after this, AI won't response.
```
AI OUTPUT: Rebooting my mind for a fresh dose of fun!
SIGNALS: AI Talking Start
SIGNALS: AI Thinking Stop
Error opening stream: [Errno -9998] Invalid number of channels
```

**Comment by kimjammer** [comment]
The TTS crashed while attempting to access your speaker. Did you configure constants.py to use the correct INPUT_DEVICE_INDEX and OUTPUT_DEVICE_INDEX? Note that these are not the same as they are in Windows, and you need to run utils/listAudioDevices.py to find the indices.
